manifest:
  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos

  projects:
    # Importa as dependências corretas a partir do repositório local
    - name: zephyr
      remote: upstream
      revision: v4.3.0
      import:
        # Filtramos apenas o que você precisa para economizar espaço
        name-allowlist:
          - acpica
          - edtt
          - fatfs
          - hal_espressif
          - hal_xtensa
          - hostap
          - liblc3
          - littlefs
          - loramac-node
          - lvgl
          - mbedtls
          - mcuboot
          - mipi-sys-t
          - net-tools
          - openthread
          - percepio
          - picolibc
          - segger
          - tinycrypt
          - uoscore-uedhoc
          - zcbor

  self:
    path: espressif-manifest
